import Head from "next/head";
import { FC, ReactNode } from "react";
import Footer from "../components/Footer";
import NavbarComponent from "../components/Navbar";

interface props {
  children: ReactNode;
}

const MainLayout: FC<props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />
      {children}
      <Footer />
    </>
  );
};

export default MainLayout;
